
+require 'vagrant-openstack-provider'
+Vagrant.configure('2') do |config |
+    config.ssh.username = ''
+    config.ssh.private_key_path = ""
+    config.vm.provider :openstack do |os, override|
+        os.identity_api_version = ENV['OS_IDENTITY_API_VERSION']
+        os.openstack_auth_url = ENV['OS_AUTH_URL']
+        os.domain_name        = ENV['OS_DOMAIN_NAME']
+        os.username           = ENV['OS_USERNAME']
+        os.password           = ENV['OS_PASSWORD']
+        os.tenant_name        = ENV['OS_TENANT_NAME']
+        os.project_name       = ENV['OS_PROJECT_NAME']
+        os.keypair_name       = ENV['OS_KEY_PAIR_NAME']
+        os.region             = ENV['OS_REGION_NAME']
+        os.image              = ENV['OS_IMAGE']
+      end
+      config.vm.define '' do |s|
+        s.vm.provision "docker"
+        s.vm.provider :openstack do |os, override|
+          os.server_name = ''
+          os.flavor = ''
+          override.vm.synced_folder '.', '/vagrant', disabled: true
+        end
+      end  
+
+      config.vm.define '' do |s|
+        s.vm.provider :openstack do |os, override|
+          os.server_name = ''
+          os.flavor = ''
+          override.vm.synced_folder '.', '/vagrant', disabled: true
+        end
+      end
+      
+      config.vm.define '' do |s|
+        s.vm.provider :openstack do |os, override|
+          os.server_name = ''
+          os.flavor = ''
+          override.vm.synced_folder '.', '/vagrant', disabled: true
+        end
+      end
+end