require 'vagrant-openstack-provider'

Vagrant.configure('2') do |config|

  config.ssh.username = 'ubuntu'
  config.ssh.private_key_path = ENV['OS_PRIVATE_KEY_PATH']

  config.vm.provider :openstack do |os, override|
    os.identity_api_version = ENV['OS_IDENTITY_API_VERSION']
    os.openstack_auth_url = ENV['OS_AUTH_URL']
    os.username           = ENV['OS_USERNAME']
    os.domain_name        = ENV['OS_DOMAIN_NAME']
    os.password           = ENV['OS_PASSWORD']
    os.tenant_name        = ENV['OS_TENANT_NAME']
    os.project_name       = ENV['OS_PROJECT_NAME']
    os.keypair_name       = ENV['OS_KEY_PAIR_NAME']
    os.region             = ENV['OS_REGION_NAME']
    os.image              = ENV['OS_IMAGE']
  end

  config.vm.define 'server-1' do |s|
    s.vm.provider :openstack do |os, override|
      os.server_name = "#{ENV['OS_INITIALS']}-ci-server"
      os.flavor = 'f2.desktop.xlarge'
      override.vm.synced_folder '.', '/vagrant', disabled: true
    end

    s.vm.provision "docker"
    s.vm.provision "shell", path:"scripts/bootstrap.sh"
    s.vm.provision "file", source: ENV['OS_PRIVATE_KEY_PATH'], destination: "$HOME/docker/jenkins/.ssh/id_rsa"
    s.vm.provision "file", source: ENV['OS_PRIVATE_KEY_PATH'], destination: "$HOME/docker/go_server/.ssh/id_rsa"
    s.vm.provision "file", source: ENV['OS_PRIVATE_KEY_PATH'], destination: "$HOME/docker/go_agent/.ssh/id_rsa"
    s.vm.provision "file", source: "docker/docker-compose.yml", destination: "$HOME/docker/docker-compose.yml"
    s.vm.provision "docker_compose", compose_version: '1.21.2', yml: "/home/ubuntu/docker/docker-compose.yml", run: "always"
  end

  config.vm.define 'server-2' do |s|
    s.vm.provision "shell", inline: "sudo apt-get install default-jdk -y"
    s.vm.provider :openstack do |os, override|
      os.server_name = "#{ENV['OS_INITIALS']}-dev-server"
      os.flavor = 'f2.desktop.large'
      override.vm.synced_folder '.', '/vagrant', disabled: true
    end
  end
  
end
